In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import torch
import time


# 1. PyTorch Fundamentals

In [3]:
# Tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7, 6])
vector

tensor([7, 7, 6])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
MATRIX = torch.tensor([[7,8],
                       [1,3]])
MATRIX 

tensor([[7, 8],
        [1, 3]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([1, 3])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
tensor = torch.tensor([[[1,2,3],
                        [1,2,3],
                        [4,5,7]],
                        [[1,2,3],
                        [1,2,3],
                        [4,5,7]]])
tensor

tensor([[[1, 2, 3],
         [1, 2, 3],
         [4, 5, 7]],

        [[1, 2, 3],
         [1, 2, 3],
         [4, 5, 7]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([2, 3, 3])

In [16]:
# Random tensors

random_tensor = torch.rand(3,4,5)
random_tensor

tensor([[[0.5786, 0.9193, 0.0039, 0.9114, 0.3793],
         [0.9904, 0.6548, 0.7795, 0.1612, 0.1240],
         [0.4920, 0.2814, 0.6887, 0.2729, 0.5704],
         [0.7770, 0.9295, 0.7051, 0.7583, 0.1834]],

        [[0.1084, 0.5903, 0.7530, 0.1873, 0.3116],
         [0.0646, 0.5100, 0.9309, 0.3601, 0.3573],
         [0.9711, 0.0974, 0.2348, 0.1654, 0.2809],
         [0.9646, 0.3011, 0.6603, 0.8046, 0.5812]],

        [[0.5529, 0.8060, 0.9054, 0.9012, 0.1060],
         [0.6327, 0.8037, 0.9180, 0.2769, 0.7388],
         [0.7644, 0.3913, 0.1918, 0.5576, 0.0891],
         [0.4489, 0.5679, 0.0484, 0.2485, 0.9738]]])

In [17]:
random_tensor.ndim

3

In [18]:
# similar shape of an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour(R,G,B)

random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [19]:
# zeros and ones

zeros = torch.zeros(3,4,5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [20]:
zeros * random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [21]:
ones = torch.ones(3,4,5)
ones

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [22]:
# range of tensors and tensors-like

one_to_ten = torch.arange(start = 0, end = 10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#tensor datatypes
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

float_32_tensor = torch.tensor([3.0,4.0,4.0],
                                dtype=torch.float32,
                                device = device,
                                requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 4., 4.], device='cuda:0'), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 16.], device='cuda:0')

In [27]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.long, device=device)

float_32_tensor * int_32_tensor

tensor([ 9., 16., 20.], device='cuda:0')

In [28]:
# getting information from tensor


some_tensor = torch.rand(3,4, device=device)
some_tensor

tensor([[0.0036, 0.8249, 0.1448, 0.0451],
        [0.2013, 0.0452, 0.3852, 0.2313],
        [0.3286, 0.4554, 0.3178, 0.1464]], device='cuda:0')

In [29]:
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cuda', index=0))

In [30]:
# manipulating tensors

tensor = torch.tensor([2,3,4],dtype=torch.float16, device=device)

tensor + 10
tensor.dtype

torch.float16

In [31]:
tensor * 10

tensor([20., 30., 40.], device='cuda:0', dtype=torch.float16)

In [32]:
tensor - 10

tensor([-8., -7., -6.], device='cuda:0', dtype=torch.float16)

In [33]:
torch.mul(tensor, 10),torch.add(tensor, 10),torch.sub(tensor, 10)

(tensor([20., 30., 40.], device='cuda:0', dtype=torch.float16),
 tensor([12., 13., 14.], device='cuda:0', dtype=torch.float16),
 tensor([-8., -7., -6.], device='cuda:0', dtype=torch.float16))

In [34]:
# matrix multiplication

torch.matmul(tensor,tensor)


tensor(29., device='cuda:0', dtype=torch.float16)

In [35]:

start = time.time()
torch.matmul(tensor,tensor)
torch.cuda.synchronize()
end = time.time()
print("Time taken:", end - start)


Time taken: 0.0


In [36]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [37]:
tensor_B = tensor_B.T
print(tensor_B)
torch.mm(tensor_A, tensor_B)

tensor([[ 7,  8,  9],
        [10, 11, 12]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
# tensor aggregation

x  = torch.arange(0,100,10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [41]:
torch.max(x), x.max()


(tensor(90), tensor(90))

In [45]:
torch.mean(x.type(torch.float)), x.type(torch.float).mean()


(tensor(45.), tensor(45.))

In [47]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [48]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [49]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [50]:
x[x.argmax()]

tensor(90)

In [61]:
# reshaping, stacking, squeezing and unsqueezing tensors

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
x_stack = torch.stack([x,x,x,x], dim = 0) 
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_reshaped, x_reshaped.shape


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [79]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape


(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [82]:
x_reshaped.unsqueeze(2)

tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [85]:
x_original = torch.rand(size = (224,224,3))
x_original.shape, x_original

(torch.Size([224, 224, 3]),
 tensor([[[0.6379, 0.1073, 0.8643],
          [0.2888, 0.0209, 0.6444],
          [0.7415, 0.1299, 0.7950],
          ...,
          [0.5552, 0.4408, 0.5081],
          [0.3050, 0.7292, 0.7092],
          [0.2790, 0.6720, 0.6520]],
 
         [[0.3690, 0.1873, 0.7725],
          [0.6581, 0.7659, 0.3828],
          [0.2598, 0.9424, 0.8848],
          ...,
          [0.6118, 0.9650, 0.3274],
          [0.8447, 0.9645, 0.8606],
          [0.6981, 0.1742, 0.8071]],
 
         [[0.3161, 0.0185, 0.0970],
          [0.0123, 0.4281, 0.9247],
          [0.7223, 0.3835, 0.1853],
          ...,
          [0.6928, 0.5704, 0.3968],
          [0.6493, 0.0128, 0.6324],
          [0.5619, 0.0435, 0.4418]],
 
         ...,
 
         [[0.8347, 0.4569, 0.7641],
          [0.5819, 0.9899, 0.7858],
          [0.8772, 0.3371, 0.7179],
          ...,
          [0.4239, 0.8703, 0.0787],
          [0.3719, 0.1300, 0.5554],
          [0.9680, 0.5607, 0.1703]],
 
         [[0.2870, 0

In [86]:
x_permuted = x_original.permute(2,0,1)
x_permuted.shape, x_permuted

(torch.Size([3, 224, 224]),
 tensor([[[0.6379, 0.2888, 0.7415,  ..., 0.5552, 0.3050, 0.2790],
          [0.3690, 0.6581, 0.2598,  ..., 0.6118, 0.8447, 0.6981],
          [0.3161, 0.0123, 0.7223,  ..., 0.6928, 0.6493, 0.5619],
          ...,
          [0.8347, 0.5819, 0.8772,  ..., 0.4239, 0.3719, 0.9680],
          [0.2870, 0.3027, 0.4693,  ..., 0.9944, 0.9758, 0.7512],
          [0.8394, 0.2339, 0.7652,  ..., 0.7544, 0.3903, 0.3814]],
 
         [[0.1073, 0.0209, 0.1299,  ..., 0.4408, 0.7292, 0.6720],
          [0.1873, 0.7659, 0.9424,  ..., 0.9650, 0.9645, 0.1742],
          [0.0185, 0.4281, 0.3835,  ..., 0.5704, 0.0128, 0.0435],
          ...,
          [0.4569, 0.9899, 0.3371,  ..., 0.8703, 0.1300, 0.5607],
          [0.6516, 0.2192, 0.5488,  ..., 0.9607, 0.4727, 0.5981],
          [0.0321, 0.7171, 0.0204,  ..., 0.4183, 0.7473, 0.9052]],
 
         [[0.8643, 0.6444, 0.7950,  ..., 0.5081, 0.7092, 0.6520],
          [0.7725, 0.3828, 0.8848,  ..., 0.3274, 0.8606, 0.8071],
          [0

In [89]:
x_original[0,0,0] = 1233
x_original[0,0,0]

tensor(1233.)

In [93]:
x_permuted[0,0,0]


tensor(1233.)

In [95]:
# indexing

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [96]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [98]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [102]:
x[0][0][0], x[0,2,2]

(tensor(1), tensor(9))

In [103]:
x[:,0]

tensor([[1, 2, 3]])

In [104]:
x[:,:,1]

tensor([[2, 5, 8]])

In [106]:
x[:, 1, 1]

tensor([5])

In [108]:
x[:,0,:]

tensor([[1, 2, 3]])

In [110]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
# pytorch tensors and numpy

array = np.arange(1.0,8.0) # numpy is float64
tensor = torch.from_numpy(array).type(torch.float32)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [113]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [114]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [119]:
# reproducibility

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A == random_tensor_B)
random_tensor_A, random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


(tensor([[0.5890, 0.2740, 0.0165, 0.7013],
         [0.7768, 0.8686, 0.6409, 0.0782],
         [0.9074, 0.0060, 0.2754, 0.7300]]),
 tensor([[0.5594, 0.3664, 0.9505, 0.4774],
         [0.6778, 0.0180, 0.2433, 0.2089],
         [0.6637, 0.0864, 0.0184, 0.5813]]))

In [122]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)


print(random_tensor_C == random_tensor_D)
random_tensor_C, random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [123]:
# running on GPUs

torch.cuda.is_available()

True

In [124]:
# setup device agnostic code

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [125]:
torch.cuda.device_count()

1

In [126]:
tensor.device

device(type='cpu')

In [136]:
tensor = torch.tensor([1,2,3], device=device)
tensor.device

device(type='cuda', index=0)

In [137]:
tensor.to("cpu").device

device(type='cpu')

In [139]:
tensor.cpu().numpy()

array([1, 2, 3])

In [142]:
# exercises 

tensor1 = torch.rand(7,7, device=device)
tensor1

tensor([[0.6130, 0.0101, 0.3984, 0.0403, 0.1563, 0.4825, 0.7362],
        [0.4060, 0.5189, 0.2867, 0.2416, 0.9228, 0.8299, 0.0342],
        [0.3879, 0.0824, 0.7742, 0.2792, 0.5138, 0.2068, 0.0074],
        [0.8750, 0.9682, 0.1201, 0.1972, 0.4503, 0.0511, 0.4892],
        [0.9331, 0.3807, 0.0509, 0.2663, 0.6495, 0.2675, 0.1733],
        [0.8565, 0.2761, 0.2093, 0.0711, 0.7701, 0.6100, 0.3444],
        [0.9852, 0.4692, 0.9203, 0.7127, 0.1052, 0.8138, 0.1092]],
       device='cuda:0')

In [ ]:
tensor2 = torch.rand(1,7, device=device)
tensor2

tensor([[0.9877, 0.1289, 0.5621, 0.5221, 0.7445, 0.5955, 0.9647]],
       device='cuda:0')

In [147]:
torch.matmul(tensor1, tensor2.T)

tensor([[1.9656],
        [1.9694],
        [1.4875],
        [1.9972],
        [1.9483],
        [2.3051],
        [2.5913]], device='cuda:0')

In [151]:
torch.manual_seed(0)
tensor1 = torch.rand(7,7, device=device)
print(tensor1)

torch.manual_seed(0)
tensor2 = torch.rand(1,7, device=device).T
print(tensor2)

torch.matmul(tensor1,tensor2)



tensor([[0.3990, 0.5167, 0.0249, 0.9401, 0.9459, 0.7967, 0.4150],
        [0.8203, 0.2290, 0.9096, 0.1183, 0.0752, 0.4092, 0.9601],
        [0.2093, 0.1940, 0.8909, 0.4387, 0.3570, 0.5454, 0.8299],
        [0.2099, 0.7684, 0.4290, 0.2117, 0.6606, 0.1654, 0.4250],
        [0.9927, 0.6964, 0.2472, 0.7028, 0.7494, 0.9303, 0.0494],
        [0.0750, 0.7223, 0.9478, 0.3647, 0.2215, 0.7784, 0.6391],
        [0.2077, 0.7045, 0.9609, 0.0594, 0.3358, 0.0616, 0.7030]],
       device='cuda:0')
tensor([[0.3990],
        [0.5167],
        [0.0249],
        [0.9401],
        [0.9459],
        [0.7967],
        [0.4150]], device='cuda:0')


tensor([[3.0122],
        [1.3752],
        [1.7349],
        [1.6234],
        [2.8933],
        [1.8644],
        [1.1851]], device='cuda:0')

In [160]:
torch.cuda.manual_seed(1234)
tensor3 = torch.rand(2,3, device=device)
torch.cuda.manual_seed(1234)
tensor4 = torch.rand(2,3, device=device)
tensor3, tensor4


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))

In [165]:
tensor_matmul1 = torch.matmul(tensor3,tensor4.T)
tensor_matmul1, tensor_matmul1.argmax(), tensor_matmul1.argmin(),tensor_matmul1.max(), tensor_matmul1.min()


(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(1, device='cuda:0'),
 tensor(1.4578, device='cuda:0'),
 tensor(0.8358, device='cuda:0'))

In [213]:
torch.manual_seed(7)
tensor5 = torch.rand(1,1,1,10, device=device)
tensor5, tensor5.shape

(tensor([[[[0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810,
            0.6333, 0.5733]]]], device='cuda:0'),
 torch.Size([1, 1, 1, 10]))

In [214]:
tensor5 = tensor5.squeeze(dim=0)
tensor5 = tensor5.squeeze()
tensor5

tensor([0.9546, 0.4950, 0.9420, 0.5926, 0.6996, 0.2087, 0.6753, 0.4810, 0.6333,
        0.5733], device='cuda:0')